// Generates every CSS output from src/tokens. Nothing in dist/ is edited by hand.
//   dist/tokens.css        custom properties, themes, density, focus, motion, base rules
//   dist/theme.css         Tailwind v4 @theme mapping onto those properties
//   dist/tokens.embed.css  the 16-token :host subset for embeds
//   dist/theme-init.js     inline pre-paint script: sets data-theme before first paint

import { mkdirSync, writeFileSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { COLOR_TOKENS, type ColorToken } from '../src/tokens/vocabulary.ts';
import { THEMES } from '../src/tokens/sets/index.ts';
import { SYSTEM_THEME, THEME_NAMES, type ThemeName } from '../src/tokens/themes.ts';
import {
  BORDER_WIDTH,
  FOCUS,
  FONT,
  FONT_SANS_EMBED,
  MOTION,
  RADIUS,
  SHADOW,
  SIZE,
  SIZE_DENSE,
  TYPE,
  Z,
} from '../src/tokens/scale.ts';
import { THEME_STORAGE_KEY } from '../src/theme/index.ts';

const OUT = new URL('../dist/', import.meta.url);
const HEADER = '/* Generated by lumux scripts/build-tokens.ts. Do not edit. */\n';

const block = (selector: string, decls: Record<string, string | number>, indent = '') =>
  `${indent}${selector} {\n${Object.entries(decls)
    .map(([k, v]) => `${indent}  ${k}: ${v};`)
    .join('\n')}\n${indent}}\n`;

const colorVars = (theme: ThemeName, only?: readonly ColorToken[]) =>
  Object.fromEntries(
    (only ?? COLOR_TOKENS).map((t) => [`--lumux-${t}`, THEMES[theme].colors[t]]),
  );

const themeVars = (theme: ThemeName) => ({ 'color-scheme': THEMES[theme].scheme, ...colorVars(theme) });

const typeVars = (variant: 'base' | 'dense') =>
  Object.fromEntries(
    Object.entries(TYPE).flatMap(([role, v]) => [
      [`--lumux-text-${role}`, v[variant].size],
      [`--lumux-text-${role}-line-height`, v[variant].lineHeight],
      [`--lumux-text-${role}-weight`, v[variant].weight],
    ]),
  );

// The one looping animation (Spinner). Under reduced motion it stops; the
// label and aria-busy still say "loading".
const SPIN = 'lumux-spin 0.9s linear infinite';

const motionOff = {
  ...Object.fromEntries((['fast', 'base', 'panel'] as const).map((k) => [`--lumux-motion-${k}`, '0.01ms'])),
  '--lumux-spin': 'none',
};

// ── tokens.css ────────────────────────────────────────────────────────────────
const scaleVars = {
  '--lumux-font-sans': FONT.sans,
  '--lumux-font-mono': FONT.mono,
  ...typeVars('base'),
  ...Object.fromEntries(Object.entries(SIZE).map(([k, v]) => [`--lumux-${k}`, v])),
  ...Object.fromEntries(Object.entries(RADIUS).map(([k, v]) => [`--lumux-radius-${k}`, v])),
  '--lumux-border-width': BORDER_WIDTH.default,
  '--lumux-border-width-emphasis': BORDER_WIDTH.emphasis,
  ...Object.fromEntries(Object.entries(SHADOW).map(([k, v]) => [`--lumux-shadow-${k}`, v])),
  ...Object.fromEntries(Object.entries(Z).map(([k, v]) => [`--lumux-z-${k}`, v])),
  ...Object.fromEntries(Object.entries(MOTION).map(([k, v]) => [`--lumux-motion-${k}`, v])),
  '--lumux-spin': SPIN,
  '--lumux-focus-width': FOCUS.width,
  '--lumux-focus-offset': FOCUS.offset,
  '--lumux-safe-top': 'env(safe-area-inset-top, 0px)',
  '--lumux-safe-right': 'env(safe-area-inset-right, 0px)',
  '--lumux-safe-bottom': 'env(safe-area-inset-bottom, 0px)',
  '--lumux-safe-left': 'env(safe-area-inset-left, 0px)',
};

const DEFAULT = SYSTEM_THEME.light;
const DEFAULT_DARK = SYSTEM_THEME.dark;
const OTHER_THEMES = THEME_NAMES.filter((t) => t !== DEFAULT);

const tokensCss =
  HEADER +
  block(':root', scaleVars) +
  `\n/* ${DEFAULT} is the default; [data-theme] on any element flips its subtree. */\n` +
  block(`:root, [data-theme="${DEFAULT}"]`, themeVars(DEFAULT)) +
  OTHER_THEMES.map((t) => block(`[data-theme="${t}"]`, themeVars(t))).join('') +
  `\n/* No data-theme on <html>: follow the OS, live, with the default pair. */\n` +
  `@media (prefers-color-scheme: dark) {\n${block(':root:not([data-theme])', themeVars(DEFAULT_DARK), '  ')}}\n` +
  '\n/* One density variant, set on a container. Type and padding only. */\n' +
  block('[data-density="dense"]', {
    ...typeVars('dense'),
    ...Object.fromEntries(Object.entries(SIZE_DENSE).map(([k, v]) => [`--lumux-${k}`, v])),
  }) +
  '\n/* AAA 2.3.3: every duration collapses. The attribute is the test hook. */\n' +
  `@media (prefers-reduced-motion: reduce) {\n${block(':root', motionOff, '  ')}}\n` +
  block('[data-reduce-motion="true"]', motionOff) +
  `
@keyframes lumux-spin {
  to {
    transform: rotate(360deg);
  }
}

@layer base {
  /* The one focus ring (AAA 2.4.13). An outline, not a box-shadow, so it
     survives forced-colors mode. Components never restyle it. */
  :focus-visible {
    outline: var(--lumux-focus-width) solid var(--lumux-focus-ring);
    outline-offset: var(--lumux-focus-offset);
  }

  @media (forced-colors: active) {
    :focus-visible {
      outline-color: Highlight;
    }
  }
}

/* iOS zooms into any field under 16px and never zooms back. Unlayered on
   purpose: it must beat a text-* utility, including the dense roles. */
@media (pointer: coarse) {
  input,
  select,
  textarea {
    font-size: max(1rem, 1em);
  }
}
`;

// ── theme.css (Tailwind v4) ───────────────────────────────────────────────────
const themeDecls: Record<string, string> = {
  ...Object.fromEntries(COLOR_TOKENS.map((t) => [`--color-${t}`, `var(--lumux-${t})`])),
  '--font-sans': 'var(--lumux-font-sans)',
  '--font-mono': 'var(--lumux-font-mono)',
  ...Object.fromEntries(
    Object.keys(TYPE).flatMap((role) => [
      [`--text-${role}`, `var(--lumux-text-${role})`],
      [`--text-${role}--line-height`, `var(--lumux-text-${role}-line-height)`],
      [`--text-${role}--font-weight`, `var(--lumux-text-${role}-weight)`],
    ]),
  ),
  ...Object.fromEntries(Object.keys(RADIUS).map((k) => [`--radius-${k}`, `var(--lumux-radius-${k})`])),
  ...Object.fromEntries(Object.keys(SHADOW).map((k) => [`--shadow-${k}`, `var(--lumux-shadow-${k})`])),
  '--spacing-target': 'var(--lumux-target-min)',
  '--spacing-header': 'var(--lumux-header-height)',
  '--spacing-sidebar': 'var(--lumux-sidebar-width)',
  '--spacing-rail': 'var(--lumux-sidebar-rail)',
  '--spacing-sheet': 'var(--lumux-sheet-width)',
  '--spacing-menu': 'var(--lumux-menu-min-width)',
  '--spacing-card': 'var(--lumux-card-padding)',
  // max-w-* reads --container-*: max-w-sheet, max-w-dialog-md.
  '--container-sheet': 'var(--lumux-sheet-width)',
  '--container-dialog-sm': 'var(--lumux-dialog-sm)',
  '--container-dialog-md': 'var(--lumux-dialog-md)',
  '--container-dialog-lg': 'var(--lumux-dialog-lg)',
  '--ease-lumux': 'var(--lumux-motion-ease)',
  '--animate-lumux-spin': 'var(--lumux-spin)',
};

const utility = (name: string, decls: Record<string, string>) => block(`@utility ${name}`, decls);

const themeCss =
  HEADER +
  '/* Import after tailwindcss and tokens.css. `inline` makes each utility carry\n' +
  '   var(--lumux-*) itself, so a subtree with its own data-theme or data-density\n' +
  '   resolves its own values. */\n' +
  block('@theme inline', themeDecls) +
  '\n' +
  Object.keys(Z)
    .map((k) => utility(`z-${k}`, { 'z-index': `var(--lumux-z-${k})` }))
    .join('') +
  (['fast', 'base', 'panel'] as const)
    .map((k) => utility(`duration-${k}`, { 'transition-duration': `var(--lumux-motion-${k})` }))
    .join('') +
  (['top', 'right', 'bottom', 'left'] as const)
    .map((side) => utility(`safe-${side}`, { [`padding-${side}`]: `var(--lumux-safe-${side})` }))
    .join('') +
  '\n/* A selected state drawn only with background disappears in forced colors,\n   where every background becomes Canvas. This paints it with the system pair. */\n' +
  '@utility forced-selected {\n  @media (forced-colors: active) {\n    forced-color-adjust: none;\n    background-color: Highlight;\n    color: HighlightText;\n  }\n}\n';

// ── tokens.embed.css (embeds) ────────────────────────────────────────────────
const EMBED_COLORS = [
  'surface',
  'surface-raised',
  'foreground',
  'foreground-muted',
  'border',
  'accent',
  'accent-foreground',
  'focus-ring',
  'overlay-scrim',
] as const satisfies readonly ColorToken[];

// Default pair only: the snippet has a byte budget and no theme switcher.
const embedColors = (theme: ThemeName) => {
  const vars = colorVars(theme, EMBED_COLORS);
  // The host page's one override.
  vars['--lumux-accent'] = `var(--lumux-embed-accent, ${THEMES[theme].colors.accent})`;
  return vars;
};

// Minified: it is copied into a stylesheet with a 3 KB gzip budget.
const minify = (css: string) =>
  css
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\s*([{}:;,])\s*/g, '$1')
    .replace(/;}/g, '}')
    .replace(/\s+/g, ' ')
    .trim() + '\n';

const embedCss = minify(
  block(':host', {
    'color-scheme': 'light',
    ...embedColors(DEFAULT),
    '--lumux-radius-control': RADIUS.control,
    '--lumux-radius-panel': RADIUS.panel,
    '--lumux-radius-pill': RADIUS.pill,
    '--lumux-font-sans': FONT_SANS_EMBED,
    '--lumux-motion-base': MOTION.base,
    '--lumux-motion-ease': MOTION.ease,
    '--lumux-target-min': SIZE['target-min'],
  }) +
  `@media (prefers-color-scheme: dark) {\n${block(':host', { 'color-scheme': 'dark', ...embedColors(DEFAULT_DARK) }, '  ')}}\n` +
  `@media (prefers-reduced-motion: reduce) {\n${block(':host', { '--lumux-motion-base': '0.01ms' }, '  ')}}\n`,
);

// ── tokens.host.css (shadow roots) ───────────────────────────────────────────
// The full token set scoped to :host, with no base rules, for UI that lives in
// shadow roots on someone else's page (e.g. an embedded studio). :root never matches
// inside a shadow root, and tokens.css's base rules must not reach the host page.
// data-theme goes on the shadow host; without it, the OS decides.
const hostCss =
  HEADER +
  block(':host', { ...scaleVars, ...themeVars(DEFAULT) }) +
  `@media (prefers-color-scheme: dark) {\n${block(':host(:not([data-theme]))', themeVars(DEFAULT_DARK), '  ')}}\n` +
  OTHER_THEMES.map((t) => block(`:host([data-theme="${t}"])`, themeVars(t))).join('') +
  block(':host([data-density="dense"]), [data-density="dense"]', {
    ...typeVars('dense'),
    ...Object.fromEntries(Object.entries(SIZE_DENSE).map(([k, v]) => [`--lumux-${k}`, v])),
  }) +
  `@media (prefers-reduced-motion: reduce) {\n${block(':host', motionOff, '  ')}}\n` +
  block(':host([data-reduce-motion="true"])', motionOff);

// ── theme-init.js ─────────────────────────────────────────────────────────────
const initJs = `try{var t=localStorage.getItem(${JSON.stringify(THEME_STORAGE_KEY)});if(${JSON.stringify(THEME_NAMES)}.indexOf(t)>-1)document.documentElement.setAttribute("data-theme",t)}catch(e){}\n`;

mkdirSync(OUT, { recursive: true });
const files: Record<string, string> = {
  'tokens.css': tokensCss,
  'theme.css': themeCss,
  'tokens.embed.css': embedCss,
  'tokens.host.css': hostCss,
  'theme-init.js': initJs,
};
for (const [name, body] of Object.entries(files)) {
  writeFileSync(new URL(name, OUT), body);
  const gz = gzipSync(body).length;
  console.log(`dist/${name.padEnd(17)} ${String(body.length).padStart(6)} B  ${String(gz).padStart(5)} B gz`);
}
